# Generated by Django 6.0.2 on 2026-05-30 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='Нікнейм')),
                ('user_class', models.CharField(blank=True, max_length=10, verbose_name='Клас (наприклад, 10-А)')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Про себе')),
                ('role', models.CharField(choices=[('student', 'Учень'), ('teacher', 'Вчитель'), ('moderator', 'Модератор'), ('admin', 'Адміністратор')], default='student', max_length=20, verbose_name='Роль')),
                ('avatar_url', models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', verbose_name='Посилання на аватарку')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
