# Generated by Django 6.0.2 on 2026-06-20 15:18

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва класу (наприклад, 10-А)')),
                ('access_type', models.CharField(choices=[('public', 'Публічний'), ('private', 'Приватний')], default='public', max_length=10, verbose_name='Тип доступу')),
                ('join_code', models.CharField(default=portal.models.generate_join_code, max_length=10, unique=True, verbose_name='Код приєднання')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_classes', to=settings.AUTH_USER_MODEL, verbose_name='Вчитель/Творець')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='Нікнейм')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Про себе')),
                ('role', models.CharField(choices=[('student', 'Учень'), ('teacher', 'Вчитель'), ('moderator', 'Модератор'), ('admin', 'Адміністратор')], default='student', max_length=20, verbose_name='Роль')),
                ('avatar_url', models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', verbose_name='Посилання на аватарку')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='portal.schoolclass', verbose_name='Клас')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата відправки')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Відправник')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.schoolclass', verbose_name='Клас')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
