# Generated by Django 6.0.2 on 2026-06-13 04:09

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_class',
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва класу (наприклад, 10-А)')),
                ('access_type', models.CharField(choices=[('public', 'Публічний'), ('private', 'Приватний')], default='public', max_length=10, verbose_name='Тип доступу')),
                ('join_code', models.CharField(default=portal.models.generate_join_code, max_length=10, unique=True, verbose_name='Код приєднання')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_classes', to=settings.AUTH_USER_MODEL, verbose_name='Вчитель/Творець')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='portal.schoolclass', verbose_name='Клас'),
        ),
    ]
