# Generated by Django 6.0.2 on 2026-06-13 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_profile_user_class_schoolclass_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата відправки')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.schoolclass', verbose_name='Клас')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Відправник')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
