# Generated by Django 6.0.2 on 2026-06-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_classmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school_class',
        ),
        migrations.AddField(
            model_name='profile',
            name='school_classes',
            field=models.ManyToManyField(blank=True, related_name='students', to='portal.schoolclass', verbose_name='Класи'),
        ),
    ]
