# Generated by Django 6.0.2 on 2026-06-13 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_profile_school_class_profile_school_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school_classes',
        ),
        migrations.AddField(
            model_name='profile',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='portal.schoolclass', verbose_name='Клас'),
        ),
    ]
