"""
Django settings for group_portal project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path

# Побудова шляхів усередині проєкту
BASE_DIR = Path(__file__).resolve().parent.parent

# НАЛАШТУВАННЯ БЕЗПЕКИ
SECRET_KEY = 'django-insecure-r44mrv3&#m150%-ew3mz#k9oj*9*fl0ue=l)94chosjxg6jdv('

DEBUG = True

ALLOWED_HOSTS = []


# СПИСОК ЗАСТОСУНКІВ
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portal',  # Наш головний застосунок
]

#ПРОМІЖНЕ ПОРТ ПЗ (MIDDLEWARE)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'group_portal.urls'

# ШАБЛОНИ (TEMPLATES)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'group_portal.wsgi.application'


# БАЗА ДАНИХ (DATABASE)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ВАЛІДАЦІЯ ПАРОЛІВ
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# МОВНІ НАЛАШТУВАННЯ ТА ЧАС
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# СТАТИЧНІ ФАЙЛИ (CSS, JS)
STATIC_URL = 'static/'

# НАЛАШТУВАННЯ АВТОРИЗАЦІЇ
# Куди перенаправляти користувача після успішного входу
LOGIN_REDIRECT_URL = 'home'
# Куди перенаправляти користувача після виходу з акаунта
LOGOUT_REDIRECT_URL = 'home'